server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



logging:
  level:
    com.example.ex: debug
  config: classpath:log4j2.yml